language: java

sudo: true

services:
  - docker

cache:
  directories:
    - $HOME/.m2
jdk:
  - oraclejdk8
os:
  - linux

script: mvn clean install

after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker image build -t learn-drop-wizard .
  - docker push alexdbondarev/learn-drop-wizard