# credit to https://github.com/alv-ch/alv-ch-java/blob/master/.travis.yml
language: java

sudo: false

services:
  - docker

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

cache:
  directories:
    - $HOME/.m2
jdk:
  - openjdk8

script: mvn clean install

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - export REPO=alexdbondarev/learn-drop-wizard
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$TAG
  - docker tag $REPO:$TAG-travis-$TRAVIS_BUILD_NUMBER-commit-$COMMIT
  - docker push $REPO