# credit to https://github.com/alv-ch/alv-ch-java/blob/master/.travis.yml
language: java

sudo: false

services:
  - docker

cache:
  directories:
    - $HOME/.m2
jdk:
  - openjdk8

script: mvn clean install

after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker image build -t learn-drop-wizard .
  - docker push alexdbondarev/learn-drop-wizard:travis_latest